### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Sureiya**
Not sure of the rationale or need to pin all the build deps, but it was failing to build.

# Proposed Changes

> Unpinned g++ and ffmpeg build dependencies so install of build dependencies would succeed.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by roblandry** [comment]
I simply updated the existing depreciated code. The issue is when the base image is updated, it changes the available versions of everything. My updates simply dug in and figured out which versions were available. If this works and builds a working install I will gladly merge. I personally haven't had the chance to test.
But in my experience, more than just the build deps change, and I've had to track down all dependencies new versions.

**Comment by roblandry** [comment]
Merged with additional changes in 23f383435a85290ed3d60cc3559f2abd6eb9077a

**Comment by Sureiya** [comment]
> Merged with additional changes in [23f3834](https://github.com/roblandry/addon-shinobi/commit/23f383435a85290ed3d60cc3559f2abd6eb9077a)

Thanks! Sorry for my lack of response. Crazy busy at work and it got lost among the work items.

**Comment by roblandry** [comment]
Not a problem, i stay pretty crazy busy too. I have it running, and all seems well now. Let me know if you find any issues.

**Comment by Sureiya** [comment]
There is an issue with ffmpeg not having the proper hardware acceleration
on it for common HA devices (raspberry pi). I've spent a lot of time
working on the issue in different contexts, but had to stop last week. If
you decide to work on it let me know and I'll document into what I found.
The best solution I believe was probably finding the right base images to
use. Debian based images should be able to add the Raspbian repositories,
which has ffmpeg build with mmal and omx. I was also looking into adding
raspberry-pi support to https://github.com/markus-perl/ffmpeg-build-script,
but it will take some work to actually get it building on HA I believe. I
was about halfway there.

Cheers

**Pull request closed without merging**
